# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='horsepower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Model'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('T', 'Tractor'), ('I', 'Implement'), ('H', 'Harvester')], max_length=1),
        ),
        migrations.AlterField(
            model_name='machine',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='horsepower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
