# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-14 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181114_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='type',
            field=models.CharField(choices=[('W', 'Plowing'), ('S', 'Sowing'), ('H', 'Harvesting'), ('F', 'Fertilization'), ('C', 'Cropcare'), ('P', 'Plantprotect')], max_length=1),
        ),
        migrations.AlterField(
            model_name='documentationfieldrelation',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Field'),
        ),
    ]
