# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181119_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantprotectantcategory',
            name='valid_cultures',
        ),
    ]
