# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181119_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Culture',
            new_name='CultureType',
        ),
    ]
