# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181119_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CultureType')),
            ],
        ),
        migrations.AlterField(
            model_name='plantprotectant',
            name='valid_cultures',
            field=models.ManyToManyField(blank=True, null=True, to='core.Culture'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Culture'),
        ),
    ]
