# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20181119_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField(default=False)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fertilizer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
