# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_fertilizerrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantProtectantRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeedRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Seed')),
            ],
        ),
        migrations.AlterField(
            model_name='plantprotectant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectantCategory'),
        ),
        migrations.AddField(
            model_name='plantprotectantrelation',
            name='plantProtectant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectant'),
        ),
    ]
