# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181119_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='status',
            field=models.CharField(choices=[('P', 'Planned'), ('S', 'Saved'), ('B', 'Booked')], default='B', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantprotectant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectantCategory'),
        ),
        migrations.AlterField(
            model_name='plantprotectantrelation',
            name='plantProtectant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectant'),
        ),
    ]
