# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181119_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprotectant',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectantCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantprotectant',
            name='valid_cultures',
            field=models.ManyToManyField(to='core.Culture'),
        ),
        migrations.AlterField(
            model_name='plantprotectantrelation',
            name='plantProtectant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectant'),
        ),
    ]
