# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181120_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantprotectantrelation',
            old_name='plantProtectant',
            new_name='plant_protectant',
        ),
        migrations.AlterField(
            model_name='plantprotectant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectantCategory'),
        ),
        migrations.AlterField(
            model_name='plantprotectantrelation',
            name='plant_protectant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectant'),
        ),
    ]
