# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181121_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationFertilizerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Documentation')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FertilizerRelation')),
            ],
        ),
        migrations.AlterField(
            model_name='plantprotectant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectantCategory'),
        ),
        migrations.AlterField(
            model_name='plantprotectantrelation',
            name='plant_protectant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectant'),
        ),
    ]
