# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181121_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationPlantProtectantRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Documentation')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationSeedRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Documentation')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SeedRelation')),
            ],
        ),
        migrations.AlterField(
            model_name='plantprotectant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectantCategory'),
        ),
        migrations.AlterField(
            model_name='plantprotectantrelation',
            name='plant_protectant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectant'),
        ),
        migrations.AddField(
            model_name='documentationplantprotectantrelation',
            name='plant_protectant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlantProtectantRelation'),
        ),
    ]
